---
- name: Generate SSH key pair
  ansible.builtin.user:
    name: "{{ local_whoami.stdout }}"
    generate_ssh_key: true
    force: true
    ssh_key_type: "{{ ssh_key_type }}"
    ssh_key_bits: "{{ ssh_key_bits }}"
    ssh_key_passphrase: ""
    ssh_key_file: "~/.ssh/{{ ssh_key_filename }}"
    state: present
  delegate_to: localhost
  register: generated_keys

- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "/home/{{ username }}/.ssh"
    mode: "0700"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
  become: true

- name: Push public key to remote host
  ansible.posix.authorized_key:
    user: "{{ username }}"
    key: "{{ generated_keys.ssh_public_key }}"
    state: present
  become: true

- name: Create a local SSH config
  ansible.builtin.blockinfile:
    dest: ~/.ssh/config
    block: |
      Host {{ ssh_config_server_alias }}
          HostName {{ ssh_target_host }}
          Port {{ ssh_port }}
          User {{ username }}
          ServerAliveInterval 120
          ServerAliveCountMax 3
          IdentityFile ~/.ssh/{{ ssh_key_filename }}
          IdentitiesOnly yes
          ForwardAgent no
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED SSH CONFIG"
    marker_begin: "{{ ssh_config_server_alias }} BEGIN"
    marker_end: "{{ ssh_config_server_alias }} END"
    append_newline: true
    create: true
    mode: "0600"
    state: present
    backup: "yes"
  delegate_to: localhost
